---
version: "2"
services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Bogota
      - UMASK_SET=022 #optional
    volumes:
      - ./sonnar/data:/config
      - ./sonnar/tv:/tv
      - ./downloads/qbit:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - webnet
    depends_on:
      - "qbittorrent"
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Bogota
      - UMASK_SET=022 #opTorrentRssIndexertional
    volumes:
      - ./radarr/data:/config
      - ./radarr/movies:/movies
      - ./downloads/qbit:/downloads
    ports:
      - 8990:7878
    restart: unless-stopped
    networks:
      - webnet
    depends_on:
      - "qbittorrent"
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Bogota
    volumes:
      - ./bazarr/data:/config
      - ./radarr/movies:/movies #optional
      - ./sonnar/tv:/tv #optional
    ports:
      - 6767:6767
    restart: unless-stopped
    networks:
      - webnet
    depends_on:
      - "sonarr"
      - "radarr"
  jellyfin:
    image: ghcr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Bogota
      - JELLYFIN_PublishedServerUrl=192.168.1.108
    volumes:
      - ./jellyfin/data:/config
      - ./sonnar/tv:/data/tvshows
      - ./radarr/movies:/data/movies
      - ./jellyfin/transcoding:/transcode #optional
    ports:
      - 8096:8096 # need to be exposed for jellyfin App.
      - 8920:8920 #optional
      - 7359:7359/udp #optional
        # - 1900:1900/udp #optional
    # devices:
    #   - /dev/dri:/dev/dri #optional
    restart: unless-stopped
    depends_on:
      - "jackett"
    networks:
      - webnet
# Qbittorrent
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Bogota
      - UMASK_SET=022
      - WEBUI_PORT=8080
    volumes:
      - ./qbittorrent:/config
      - ./downloads/qbit/:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    restart: unless-stopped
    networks:
      - webnet
  nginx:
    image: linuxserver/nginx
    container_name: nginx
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Bogota
    volumes:
      - ./nginx:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    depends_on:
      - "qbittorrent"
      - "jellyfin"
      - "sonarr"
      - "radarr"
    networks:
      - webnet
  jackett:
    image: ghcr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Bogota
    volumes:
      - ./jackett/config:/config
      - ./downloads/qbit:/downloads
    ports:
      - 9117:9117
    depends_on:
      - "flaresolverr"
    networks:
      - webnet
    restart: unless-stopped
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Bogota
    ports:
        - 8191:8191
    networks:
      - webnet
  openbooks:
    image: evanbuss/openbooks
    container_name: openbooks
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Bogota
      - BASE_PATH=/book/
    ports:
        - 8900:80
    volumes:
      - ./downloads/qbit:/books
    networks:
      - webnet
networks:
  webnet:
